name: Deploy to EKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build & Push Docker image
      run: |
        docker build -t your-dockerhub-username/gemini-frontend:latest ./frontend
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u your-dockerhub-username --password-stdin
        docker push your-dockerhub-username/gemini-frontend:latest

    - name: Update K8s manifests
      run: |
        kubectl config use-context arn:aws:eks:ap-south-1:XXXXXX:cluster/eksnaren
        kubectl apply -f k8s/

