name: Deploy to EKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build & Push Docker image
      run: |
        docker build -t narenreddy1/gemini:latest ./frontend
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push narenreddy1/gemini:latest

    - name: Update K8s manifests
      run: |
        kubectl config use-context arn:aws:eks:us-east-1:970107227636:cluster/naren-cluster
        kubectl apply -f k8s/

